### ISSUE TITLE
建议把awardLength设成变量，不然添加了奖项转盘会有bug

### ISSUE THREAD

**Issue by xavieryang2011** [givebest/wechat-turntalbe-canvas#1]
getLottery: function () {
    var that = this
    var awardIndex = Math.random() * awardLength >>> 0;

    // 获取奖品配置
    var awardsConfig = app.awardsConfig,
      runNum = awardLength+2
    if (awardIndex < 2) awardsConfig.chance = false
    console.log(awardIndex)

**Comment by givebest** [comment]
好主意
